[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
core_project = "HHuJZNCk51Zz3KtBfAxpzMsMHWR94W9KUoErhsMUVreL"

[programs.devnet]
core_project = "HHuJZNCk51Zz3KtBfAxpzMsMHWR94W9KUoErhsMUVreL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"